@host = http://ec2-13-229-237-54.ap-southeast-1.compute.amazonaws.com:5001/api/v2
@token = 75921f4e01b6caad0dc2d0f966b876da
#health check
GET {{host}}


### update all document --- BE CAREFUL
GET {{host}}/document/all


### update all document into postgres --- BE CAREFUL
GET {{host}}/documentpostgre/all

###
# get chat history
GET {{host}}/chat?chatid=3
Content-Type: application/json
Authorization: Bearer {{token}}

###
# send message
POST {{host}}/chat
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "content": "make a poetry about cloud",
    "chatId": 2,
    "role": 1,
    "courseId": 11
}
###
# send message
POST {{host}}/chat
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "content": "Tôi đang có những khóa học nào",
    "chatId": 2,
    "role": 2,
    "courseId": 11
}
### 
# delete chat
DELETE {{host}}chat?chatid=2
Authorization: Bearer {{token}}


###
GET {{host}}/get_user_info
Content-Type: application/json
Authorization: Bearer {{token}}



### SET UP TIME REMINDER
POST {{host}}/settime
Content-Type: application/json

{
    "user_id": 2,
    "status": 1,
    "time": "02:51"
}


### GET UP TIME REMINDER
GET {{host}}/gettime
Content-Type: application/json


###
POST {{host}}/reminder
Content-Type: application/json

{
    "name": "quiz",
    "title": "câu hỏi ôn tập",
    "user_id": 3,
    "user": "Phat",
    "course_id": 2,
    "course": "Nôm",
    "type_action": "was created",
    "time_action": "2024-10-14 00:57:02",
    "time_reminder": "2024-10-14 00:57:02"
}


