#health check
GET http://localhost:8000/api/v1/

# get chat history
###
GET http://localhost:8000/api/v1/chat?chatid=2
Content-Type: application/json
Authorization: Bearer c53719b17b93ba017e6864ff3adb3e28

###
# send message
POST http://localhost:8000/api/v1/chat
Content-Type: application/json

{
    "content": "Các tác phẩm thơ nôm",
    "chatId": 2,
    "role": 1
}
### 
# delete chat
DELETE http://localhost:8000/api/v1/chat/2
 


###
GET http://localhost:8000/api/v1/get_user_info
Content-Type: application/json
Authorization: Bearer c53719b17b93ba017e6864ff3adb3e28