#health check
GET https://ec2-47-129-187-231.ap-southeast-1.compute.amazonaws.com:5001/api/v2/


### update all document --- BE CAREFUL
GET http://localhost:5001/api/v1/document/all


### update all document into postgres --- BE CAREFUL
GET http://localhost:5001/api/v2/documentpostgre/all

###
# get chat history
GET http://ec2-13-212-109-15.ap-southeast-1.compute.amazonaws.com:5001/api/v2/
Content-Type: application/json
Authorization: Bearer 75921f4e01b6caad0dc2d0f966b876da


###
GET http://ec2-13-212-109-15.ap-southeast-1.compute.amazonaws.com:5001/api/v2/chat?chatid=2
Content-Type: application/json
Authorization: Bearer 75921f4e01b6caad0dc2d0f966b876da

###
GET http://localhost:5001/api/v2/chat?chatid=3
Content-Type: application/json
Authorization: Bearer 75921f4e01b6caad0dc2d0f966b876da
###
# send message
POST http://localhost:5001/api/v2/chat
Content-Type: application/json

{
    "content": "make a poetry about cloud",
    "chatId": 2,
    "role": 1,
    "courseId": 11
}
###
# send message
POST http://ec2-13-212-109-15.ap-southeast-1.compute.amazonaws.com:5001/api/v2/chat
Content-Type: application/json

{
    "content": "Tôi đang có những khóa học nào",
    "chatId": 2,
    "role": 3,
    "courseId": 11
}
### 
# delete chat
DELETE http://localhost:5001/api/v2/chat?chatid=2
 


###
GET http://localhost:5001/api/v2/get_user_info
Content-Type: application/json
Authorization: Bearer 75921f4e01b6caad0dc2d0f966b876da



### SET UP TIME REMINDER
POST http://localhost:5001/api/v2/settime
Content-Type: application/json

{
    "user_id": 2,
    "status": 1,
    "time": "22:54"
}




###
POST http://localhost:5001/api/v2/reminder
Content-Type: application/json

{
    "name": "quiz",
    "title": "câu hỏi ôn tập",
    "user_id": 3,
    "user": "Phat",
    "course_id": 2,
    "course": "Nôm",
    "type_action": "was created",
    "time_action": "2024-10-14 00:57:02",
    "time_reminder": "2024-10-14 00:57:02"
}


