@host = http://localhost:5001/api/v2
@token = 832be2bcb454b8a051d0ee870ddf1027
@session = bvaask7jt8q31pgv7nj8ufhipt



####
GET {{host}}/token?userId=2
Content-Type: application/json
Authorization: Bearer {{token}}

####
#health check
GET {{host}}

###
#GET TOKEN
GET {{host}}/token?userId=3

### update all document --- BE CAREFUL
GET {{host}}/document/all


### update all document into postgres --- BE CAREFUL
GET {{host}}/documentpostgre/all


### update all document into postgres --- BE CAREFUL
GET {{host}}/documentpostgre?id=21
Content-Type: application/json
Authorization: Bearer {{token}}






###
# get chat history
GET {{host}}/chat?chatid=2
Content-Type: application/json
Authorization: Bearer {{token}}

###
# send message
POST {{host}}/chat
Content-Type: application/json
Authorization: Bearer aa

{
    "content": "hi",
    "chatId": 1,
    "role": 0,
    "courseId": 11
}
###
# send message
POST {{host}}/chat
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "content": "Tôi đang có những khóa học nào",
    "chatId": 3,
    "role": 2,
    "courseId": 11
}
###
# delete chat
DELETE {{host}}/chat?chatid=3
Authorization: Bearer {{token}}


###
GET {{host}}/get_user_info
Content-Type: application/json
Authorization: Bearer {{token}}



### SET UP TIME REMINDER
POST {{host}}/settime
Content-Type: application/json

{
    "user_id": 2,
    "status": 1,
    "time": "22:54"
}

### GET UP TIME REMINDER
GET {{host}}/gettime
Content-Type: application/json

###
POST {{host}}/reminder
Content-Type: application/json

{
    "name": "quiz",
    "title": "câu hỏi ôn tập",
    "user_id": 2,
    "user": "Phat",
    "course_id": 2,
    "course": "Nôm",
    "type_action": "was created",
    "time_action": "2024-10-14 00:57:02",
    "time_reminder": "2024-10-14 00:57:02"
}


####
POST {{host}}/verify
Content-Type: application/json

{
  "password": "1307x2Npk.",
  "username": "phat"
}






