"""reminder table

Revision ID: 0be0cb4c1fcb
Revises: 51e52e182426
Create Date: 2024-05-01 22:56:47.051653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0be0cb4c1fcb'
down_revision: Union[str, None] = '51e52e182426'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages_reminders_chatbot',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('QUIZ', 'ASSIGN', 'PAGE', name='remindertype'), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('chatId', sa.Integer(), nullable=False),
    sa.Column('time_remind', sa.DateTime(), nullable=False),
    sa.Column('is_remind', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages_reminders_chatbot')
    # ### end Alembic commands ###
