"""reminder adjust

Revision ID: 36f96db9aeb1
Revises: 0be0cb4c1fcb
Create Date: 2024-05-03 11:22:06.438233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36f96db9aeb1'
down_revision: Union[str, None] = '0be0cb4c1fcb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
