"""reminder delete enum

Revision ID: 6504b576618e
Revises: 36f96db9aeb1
Create Date: 2024-05-03 11:27:30.264042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel
# revision identifiers, used by Alembic.
revision: str = '6504b576618e'
down_revision: Union[str, None] = '36f96db9aeb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages_reminders_chatbot', 'type',
               existing_type=postgresql.ENUM('QUIZ', 'ASSIGN', 'PAGE', name='remindertype'),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages_reminders_chatbot', 'type',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=postgresql.ENUM('QUIZ', 'ASSIGN', 'PAGE', name='remindertype'),
               existing_nullable=False)
    # ### end Alembic commands ###
