"""add page

Revision ID: 3c1a4fd3b8ff
Revises: d3de43b2e142
Create Date: 2024-04-25 12:07:26.557667

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel 

# revision identifiers, used by Alembic.
revision: str = '3c1a4fd3b8ff'
down_revision: Union[str, None] = 'd3de43b2e142'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mdl_page',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('intro', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('introformat', sa.Integer(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('contentformat', sa.Integer(), nullable=False),
    sa.Column('legacyfiles', sa.Integer(), nullable=False),
    sa.Column('legacyfileslast', sa.Integer(), nullable=False),
    sa.Column('display', sa.Integer(), nullable=False),
    sa.Column('displayoptions', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('revision', sa.Integer(), nullable=False),
    sa.Column('timemodified', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mdl_page')
    # ### end Alembic commands ###
