"""label table

Revision ID: 42a21a495eb0
Revises: b7e881a36e06
Create Date: 2024-04-25 14:40:35.708054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
# revision identifiers, used by Alembic.
revision: str = '42a21a495eb0'
down_revision: Union[str, None] = 'b7e881a36e06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    pass
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('mdl_label',
    # sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('course', sa.Integer(), nullable=False),
    # sa.Column('name', sa.String(length=255, collation='C.UTF-8'), nullable=True),
    # sa.Column('intro', sa.String(length=255, collation='C.UTF-8'), nullable=True),
    # sa.Column('introformat', sa.Integer(), nullable=True),
    # sa.PrimaryKeyConstraint('id')
    # )
    # ### end Alembic commands ###


def downgrade() -> None:
    pass
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('mdl_label')
    # ### end Alembic commands ###
