"""label column

Revision ID: 51e52e182426
Revises: 8921633bf080
Create Date: 2024-04-25 14:52:33.651934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '51e52e182426'
down_revision: Union[str, None] = '8921633bf080'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mdl_label', sa.Column('timemodified', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mdl_label', 'timemodified')
    # ### end Alembic commands ###
