"""change enrol table

Revision ID: 82005978cce3
Revises: 4d08341b5953
Create Date: 2024-04-24 11:14:23.843677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '82005978cce3'
down_revision: Union[str, None] = '4d08341b5953'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.alter_column('mdl_enrol', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('mdl_enrol', 'enrolperiod',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('mdl_enrol', 'enrolstartdate',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('mdl_enrol', 'enrolenddate',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('mdl_enrol', 'expirynotify',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('mdl_enrol', 'expirythreshold',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('mdl_enrol', 'notifyall',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('mdl_enrol', 'password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('mdl_enrol', 'cost',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('mdl_enrol', 'currency',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('mdl_enrol', 'roleid',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('mdl_enrol', 'customint1',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('mdl_enrol', 'customint2',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('mdl_enrol', 'customint3',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('mdl_enrol', 'customint4',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('mdl_enrol', 'customint5',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('mdl_enrol', 'customint6',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('mdl_enrol', 'customint7',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('mdl_enrol', 'customint8',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('mdl_enrol', 'customchar1',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('mdl_enrol', 'customchar2',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('mdl_enrol', 'customchar3',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('mdl_enrol', 'customdec1',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('mdl_enrol', 'customdec2',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('mdl_enrol', 'customtext1',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('mdl_enrol', 'customtext2',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('mdl_enrol', 'customtext3',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('mdl_enrol', 'customtext4',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('mdl_enrol', 'timecreated',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('mdl_enrol', 'timemodified',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mdl_enrol', 'timemodified',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('mdl_enrol', 'timecreated',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('mdl_enrol', 'customtext4',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('mdl_enrol', 'customtext3',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('mdl_enrol', 'customtext2',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('mdl_enrol', 'customtext1',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('mdl_enrol', 'customdec2',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('mdl_enrol', 'customdec1',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('mdl_enrol', 'customchar3',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('mdl_enrol', 'customchar2',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('mdl_enrol', 'customchar1',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('mdl_enrol', 'customint8',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('mdl_enrol', 'customint7',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('mdl_enrol', 'customint6',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('mdl_enrol', 'customint5',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('mdl_enrol', 'customint4',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('mdl_enrol', 'customint3',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('mdl_enrol', 'customint2',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('mdl_enrol', 'customint1',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('mdl_enrol', 'roleid',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('mdl_enrol', 'currency',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('mdl_enrol', 'cost',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('mdl_enrol', 'password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('mdl_enrol', 'notifyall',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('mdl_enrol', 'expirythreshold',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('mdl_enrol', 'expirynotify',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('mdl_enrol', 'enrolenddate',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('mdl_enrol', 'enrolstartdate',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('mdl_enrol', 'enrolperiod',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('mdl_enrol', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
