"""page vi 1

Revision ID: b7e881a36e06
Revises: 6bef2fa4b833
Create Date: 2024-04-25 12:53:50.398969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'b7e881a36e06'
down_revision: Union[str, None] = '6bef2fa4b833'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mdl_page', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('mdl_page', 'intro',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('mdl_page', 'content',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mdl_page', 'content',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('mdl_page', 'intro',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('mdl_page', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
