"""adjust assign again

Revision ID: bfd4f2170fcd
Revises: f86a3a02e852
Create Date: 2024-04-24 11:05:04.320180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'bfd4f2170fcd'
down_revision: Union[str, None] = 'f86a3a02e852'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:

    op.alter_column('mdl_course', 'downloadcontent',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('mdl_course', 'originalcourseid',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('mdl_course', 'showactivitydates',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('mdl_course', 'showcompletionconditions',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('mdl_course', 'pdfexportfont',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mdl_course', 'pdfexportfont',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('mdl_course', 'showcompletionconditions',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('mdl_course', 'showactivitydates',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('mdl_course', 'originalcourseid',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('mdl_course', 'downloadcontent',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
