"""add message table

Revision ID: d3de43b2e142
Revises: 82005978cce3
Create Date: 2024-04-24 11:28:23.205198

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'd3de43b2e142'
down_revision: Union[str, None] = '82005978cce3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages_chatbot',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('chatId', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('BOT', 'USER', name='typerolechoices'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages_chatbot_deleted',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('chatId', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('BOT', 'USER', name='typerolechoices'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages_chatbot_deleted')
    op.drop_table('messages_chatbot')
    # ### end Alembic commands ###
