"""page adjust

Revision ID: e051347b3acf
Revises: 3c1a4fd3b8ff
Create Date: 2024-04-25 12:13:33.902288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'e051347b3acf'
down_revision: Union[str, None] = '3c1a4fd3b8ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mdl_page', 'legacyfileslast',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('mdl_page', 'display',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('mdl_page', 'displayoptions',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('mdl_page', 'revision',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('mdl_page', 'timemodified',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mdl_page', 'timemodified',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('mdl_page', 'revision',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('mdl_page', 'displayoptions',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('mdl_page', 'display',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('mdl_page', 'legacyfileslast',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
